### PR TITLE
[Add] Metabolomics support

### PR DESCRIPTION
**Pull request by oliveralka**
Initial change to read and process metabolomics data. 

Please let me know what you think in terms of code style and if you have further suggestions. 

I will try to add a test as well later on. 

The change in "R/get_peaks_chromatograms.R " is due to the fact that in some cases only one transition is processed.
There might be Problems with the other XICFilter methods due to this. 

Please let me know if you would like to have further data for testing purposes.

### CODE REVIEW

**Comment by shubham1637** [comment]
I have fixed changes in this branch: https://github.com/Roestlab/DIAlignR/tree/oliveralka-add/metabolomics_support Didn't know how to add them to yours without master.
- Mainly, I kept default argument (runType = DIA_Proteomics) to make sure tests don't fail because I may have not added this argument in all tests.
- Use `devtools::test()` to test your changes.
- Add relevant tests in tests/testthat directory.
- Use `devtools::check()` to test examples.

**Comment by oliveralka** [comment]
Added test for metabolomics - I am not sure about the "Skipped" one. 
```
RScript testthat.R
[1] "hroest_K120808_Strep10%PlasmaBiolRepl1_R03_SW_filt"
[2] "hroest_K120809_Strep0%PlasmaBiolRepl2_R04_SW_filt" 
[3] "hroest_K120809_Strep10%PlasmaBiolRepl2_R04_SW_filt"
Time difference of 0.4763839 secs
[1] "hroest_K120808_Strep10%PlasmaBiolRepl1_R03_SW_filt"
[2] "hroest_K120809_Strep0%PlasmaBiolRepl2_R04_SW_filt" 
Time difference of 0.2920501 secs
[1] "hroest_K120809_Strep0%PlasmaBiolRepl2_R04_SW_filt" 
[2] "hroest_K120809_Strep10%PlasmaBiolRepl2_R04_SW_filt"
[1] "PestMix1_8Step1Plasma1SWATH20-50" "PestMix1_8Step8Plasma1SWATH20-50"
Time difference of 0.239465 secs
══ testthat results  ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ OK: 200 | SKIPPED: 1 | WARNINGS: 0 | FAILED: 0 ]
```

```
> devtools::test()
Loading DIAlignR
Testing DIAlignR
✔ |  OK F W S | Context
✔ |  21       | Rmain.cpp [0.2 s]
⠏ |   0       | Align DIA runs[1] "hroest_K120808_Strep10%PlasmaBiolRepl1_R03_SW_filt"
[2] "hroest_K120809_Strep0%PlasmaBiolRepl2_R04_SW_filt" 
[3] "hroest_K120809_Strep10%PlasmaBiolRepl2_R04_SW_filt"
Time difference of 0.547328 secs
⠋ |   1       | Align DIA runs[1] "hroest_K120808_Strep10%PlasmaBiolRepl1_R03_SW_filt"
[2] "hroest_K120809_Strep0%PlasmaBiolRepl2_R04_SW_filt" 
Time difference of 0.3124101 secs
⠦ |  17       | Align DIA runs[1] "hroest_K120809_Strep0%PlasmaBiolRepl2_R04_SW_filt" 
[2] "hroest_K120809_Strep10%PlasmaBiolRepl2_R04_SW_filt"
⠹ |  33       | Align DIA runs[1] "PestMix1_8Step1Plasma1SWATH20-50" "PestMix1_8Step8Plasma1SWATH20-50"
Time difference of 0.2437148 secs
✔ |  57       | Align DIA runs [2.7 s]
✔ |  11       | Smoothing chromatograms
✔ |   5       | Fetching analytes names.
✔ |   9       | Read osw mzML files.
✔ |  16       | Global Fit [0.2 s]
✔ |   7       | Query
✔ |  14       | get_peak_chromatograms [0.2 s]
✔ |  10       | Merging OSW and mzML files. [0.5 s]
✔ |   7       | Pairwise analyte peak correspondence.
✔ |   5     1 | Post alignment analysis
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test_post_alignment.R:37: skip: test_setAlignmentRank
Reason: empty test
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ |   6       | Read mzml files.
✔ |  19       | Read osw files. [0.2 s]
✔ |  13       | Utility functions [0.9 s]

══ Results ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 5.3 s

OK:       200
Failed:   0
Warnings: 0
Skipped:  1
```

```
> devtools::check()
Updating DIAlignR documentation
Loading DIAlignR
Writing NAMESPACE
Writing NAMESPACE
── Building ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── DIAlignR ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/Users/alka/Documents/work/software/DIAlignR/DESCRIPTION’ ...
─  preparing ‘DIAlignR’: (677ms)
✔  checking DESCRIPTION meta-information
─  cleaning src
─  installing the package to build vignettes
✔  creating vignettes (32.2s)
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘DIAlignR_1.1.5.tar.gz’
   
── Checking ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── DIAlignR ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
● _R_CHECK_CRAN_INCOMING_       : FALSE
● _R_CHECK_FORCE_SUGGESTS_      : FALSE
● NOT_CRAN                      : true
── R CMD check ─────────────────────────────────────────────────────────────────
─  using log directory ‘/private/var/folders/t7/x82jn_jd09vc_hlq_sqs2jlw0000gn/T/RtmpidfUzt/DIAlignR.Rcheck’
─  using R version 4.0.2 (2020-06-22)
─  using platform: x86_64-apple-darwin17.0 (64-bit)
─  using session charset: UTF-8
─  using options ‘--no-manual --as-cran’ (488ms)
✔  checking for file ‘DIAlignR/DESCRIPTION’
─  checking extension type ... Package
─  this is package ‘DIAlignR’ version ‘1.1.5’
─  package encoding: UTF-8
✔  checking package namespace information ...
N  checking package dependencies (4.2s)
   Package suggested but not available for checking: ‘BiocStyle’
✔  checking if this is a source package
✔  checking if there is a namespace
✔  checking for executable files (1.1s)
✔  checking for hidden files and directories
✔  checking for portable file names ...
✔  checking for sufficient/correct file permissions
✔  checking serialization versions
W  checking whether package ‘DIAlignR’ can be installed (25s)
   Found the following significant warnings:
     chromSimMatrix.cpp:288:69: warning: 'ptr_fun<double, double>' is deprecated [-Wdeprecated-declarations]
   See ‘/private/var/folders/t7/x82jn_jd09vc_hlq_sqs2jlw0000gn/T/RtmpidfUzt/DIAlignR.Rcheck/00install.out’ for details.
N  checking installed package size ...
     installed size is  7.8Mb
     sub-directories of 1Mb or more:
       extdata   3.6Mb
       metabo    3.3Mb
✔  checking package directory ...
✔  checking for future file timestamps (720ms)
✔  checking DESCRIPTION meta-information ...
N  checking top-level files
   Non-standard file/directory found at top level:
     ‘DIAlignR_1.1.5.tar.gz’
✔  checking for left-over files
✔  checking index information ...
✔  checking package subdirectories ...
✔  checking R files for non-ASCII characters ...
✔  checking R files for syntax errors ...
✔  checking whether the package can be loaded (648ms)
✔  checking whether the package can be loaded with stated dependencies (783ms)
✔  checking whether the package can be unloaded cleanly (648ms)
✔  checking whether the namespace can be loaded with stated dependencies (582ms)
✔  checking whether the namespace can be unloaded cleanly (641ms)
✔  checking dependencies in R code (1.7s)
✔  checking S3 generic/method consistency (1.7s)
✔  checking replacement functions (639ms)
✔  checking foreign function calls (747ms)
✔  checking R code for possible problems (5.1s)
✔  checking Rd files (409ms)
✔  checking Rd metadata ...
✔  checking Rd line widths ...
✔  checking Rd cross-references ...
✔  checking for missing documentation entries (717ms)
W  checking for code/documentation mismatches (776ms)
   Variables with usage in documentation object 'XIC_QFNNTDIVLLEDFQK_3_DIAlignR' but not in code:
     ‘XIC_QFNNTDIVLLEDFQK_3_DIAlignR’
   
   Variables with usage in documentation object 'multipeptide_DIAlignR' but not in code:
     ‘multipeptide_DIAlignR’
   
   Variables with usage in documentation object 'oswFiles_DIAlignR' but not in code:
     ‘oswFiles_DIAlignR’
   
✔  checking Rd \usage sections (3.5s)
✔  checking Rd contents ...
✔  checking for unstated dependencies in examples ...
✔  checking contents of ‘data’ directory (822ms)
✔  checking data for non-ASCII characters ...
✔  checking data for ASCII and uncompressed saves ...
✔  checking line endings in C/C++/Fortran sources/headers ...
✔  checking pragmas in C/C++ headers and code ...
✔  checking compilation flags used
✔  checking compiled code ...
✔  checking installed files from ‘inst/doc’ ...
✔  checking files in ‘vignettes’ ...
✔  checking examples (10.8s)
✔  checking for unstated dependencies in ‘tests’ ...
─  checking tests ...
✔  Running ‘testthat.R’ (6.2s)
✔  checking for unstated dependencies in vignettes (6.5s)
✔  checking package vignettes in ‘inst/doc’
✔  checking re-building of vignette outputs (5.8s)
N  checking for non-standard things in the check directory
   Found the following files/directories:
     ‘AlignedAnalytes.pdf’ ‘testDIAlignR.csv’
✔  checking for detritus in the temp directory
   
   See
     ‘/private/var/folders/t7/x82jn_jd09vc_hlq_sqs2jlw0000gn/T/RtmpidfUzt/DIAlignR.Rcheck/00check.log’
   for details.
   
   
── R CMD check results ───────────────────────────────────── DIAlignR 1.1.5 ────
Duration: 1m 17.4s

❯ checking whether package ‘DIAlignR’ can be installed ... WARNING
  See below...

❯ checking for code/documentation mismatches ... WARNING
  Variables with usage in documentation object 'XIC_QFNNTDIVLLEDFQK_3_DIAlignR' but not in code:
    ‘XIC_QFNNTDIVLLEDFQK_3_DIAlignR’
  
  Variables with usage in documentation object 'multipeptide_DIAlignR' but not in code:
    ‘multipeptide_DIAlignR’
  
  Variables with usage in documentation object 'oswFiles_DIAlignR' but not in code:
    ‘oswFiles_DIAlignR’

❯ checking package dependencies ... NOTE
  Package suggested but not available for checking: ‘BiocStyle’

❯ checking installed package size ... NOTE
    installed size is  7.8Mb
    sub-directories of 1Mb or more:
      extdata   3.6Mb
      metabo    3.3Mb

❯ checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘DIAlignR_1.1.5.tar.gz’

❯ checking for non-standard things in the check directory ... NOTE
  Found the following files/directories:
    ‘AlignedAnalytes.pdf’ ‘testDIAlignR.csv’

0 errors ✔ | 2 warnings ✖ | 4 notes ✖
```

**Comment by oliveralka** [comment]
@shubham1637 Thanks for your help and the call - please let me know if further changes are necessary!

**Comment by oliveralka** [comment]
@shubham1637 Could you please take a look?

**Comment by shubham1637** [comment]
Done. Thanks Oliver!

**Pull request merged**
