### PR TITLE
Feature/speed

### PR DESCRIPTION
**Pull request by hroest**
Provides another 3x speedup in the C++ code:

before:
```
real    0m0.899s
user    0m0.780s
sys     0m0.116s
```

after:
```
real    0m0.290s
user    0m0.212s
sys     0m0.076s
```

this is based on a few heuristics and should be first tested on some real data (i only used dummy data here). Optimizations:

- use raw arrays instead of STL templates
- replace `std::cos(2*std::acos(i));` with a pre-computed lookup table
- use `std::nth_element` for quantile computation (now the complexity should go down from `2 N^2 log(N) )` to `N^2` possibly for the whole algorithm
- use copy elision for the large matrices

Compared to the R code, we observe a 4x to 6x speedup with a runtime of 300 micro-seconds for a large example (6x 2000 RT points) and 1.55 micro-seconds for a small example (6x 200 RT points). With this we should be able to align two runs with 100k peptide precursors each in about 2.5 minutes.

### CODE REVIEW

**Comment by shubham1637** [comment]
With `namespace` we are narrowing the scope of all the variables. https://www.geeksforgeeks.org/namespace-in-c/

**Comment by hroest** [comment]
Yes and this is a good thing. If another library wants to use the code such
as OpenMS then the variables are clearly distinct and there is no clash of
variables. Imagine that other libraries have their own quantile function
and you would break compilation if you have two implementations with the
same name. It's good practice in software engineering.

**Comment by shubham1637** [comment]
- namespace narrows the scope of a function and reduces possible future conflicts. To use such functions at the global level we need to use namespace::function, this practice also adds readability.

- std::nth_element is a partial sort algorithm and faster [O(n)] than sorting the whole vector [O(n^2)].

- #if is a preprocessor directive and should be introduced at the same level as #inclue (thus no tab space). We have left them in the code to check performance. If the condition is true, a compiler doesn't even look at the #else code, and vice-versa.

- Trigonometric calculations are expensive. The possible implementation could be CORDIC implementation, Taylor series or its own look-up table. However, when we have our own small look-up table, we get a higher speed. https://stackoverflow.com/questions/345085/how-do-trigonometric-functions-work

- Native build uses lowest level binaries possible as we ask to run on host operating system. Thus, cmake does some optimization for host OS. Another way could be to build it on a virtual machine where the optimization won't be possible. https://stackoverflow.com/questions/15607709/what-is-a-native-build-environment

**Comment by shubham1637** [comment]
- copy elision to avoid deep copy overhead. Usually `=` means copy constructor which is expensive as it copies every element of a temporary object to LHS. We want to omit copy and therefore use better coding practice:
Instead of 
```
AffineAlignObj obj(m,n);
obj = doAffineAlignment(...);
```
we use 
`AffineAlignObj obj = doAffineAlignment(...);`
It just moves the obj pointer to the returned object of function, thus avoids deep copy.
https://www.geeksforgeeks.org/copy-elision-in-c/

- STL objects are safe, hence, require some overhead. With naked pointers, we can avoid that overhead and gain some slight increase in speed. However, there could be issues related to memory clean-up (memory leak) so proper coding practice is needed.

**Comment by shubham1637** [comment]
@hroest 
We don't use SRC_LIST variable defined in `aux_source_directory(. SRC_LIST)`. What is the use of it?
What is the use of cache string in this line `set(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)`?

**Review by shubham1637 — COMMENTED** [review]
`Vec2NumericMatrix` and `EnumToChar` breaks if we switch from manual memory allocation instead of STL vector. Considering the current design, we are not ready to make a change to manual memory allocation. Once all the tests are complete, I think we need to keep using STL containers as major code change is needed.

**Comment by hroest** [comment]
> `Vec2NumericMatrix` and `EnumToChar` breaks if we switch from manual memory allocation instead of STL vector.

this is easy to fix, you can use `NumericMatrix` instead of  `Vec2NumericMatrix` see f32b81e 

>     * STL objects are safe, hence, require some overhead. With naked pointers, we can avoid that overhead and gain some slight increase in speed. However, there could be issues related to memory clean-up (memory leak) so proper coding practice is needed.

I agree, however in this case its a major increase in speed we are looking at. It is therefore worthwhile to use raw memory allocation

> 
> we use
> 
> `AffineAlignObj obj = doAffineAlignment(...);`
> 
> It just moves the obj pointer to the returned object of function, thus avoids deep copy.

even better is to use `void doAffineAlignment(AffineAlignObj&,` because this leaves it up to the caller on where and how memory is allocated. The idea is that you could reuse the same object over and over without re-allocating memory. Basically the idea is that you can pre-allocate a similarity matrix for a few common cases and then simply use the correctly sized matrix:

```
if (size < 128)
  static AffineAlignObj o(128, 128);
if (size < 256)
  static AffineAlignObj o(256, 256);
if (size < 512)
  static AffineAlignObj o(512, 512);
if (size < 1024)
  static AffineAlignObj o(1024, 1024);
```

and then pick the right one for analysis. So the object is only created once and and the right size object is picked without ever having to allocate an object

**Comment by shubham1637** [comment]
Thanks, Hannes.
I tried to build it in R by having `#define USE_Rcpp`. This avoids multiple main() files issue. However, I can't build it when I use feature/speed branch.
```
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘DIAlignR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/shubham/R/x86_64-pc-linux-gnu-library/3.4/DIAlignR/libs/DIAlignR.so':
  /home/shubham/R/x86_64-pc-linux-gnu-library/3.4/DIAlignR/libs/DIAlignR.so: undefined symbol: _Z16initializeMatrixdii
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/shubham/R/x86_64-pc-linux-gnu-library/3.4/DIAlignR’
* restoring previous ‘/home/shubham/R/x86_64-pc-linux-gnu-library/3.4/DIAlignR’

Exited with status 1.
```
I think it could be because `R/RcppExports.R` and `src/RcppExports.cpp` or some other issue. Could you please check on your machine?

**Comment by shubham1637** [comment]
On building the package in R, R updates `src/RcppExports.cpp` and removes `using namespace DIAlign;`
I assume it is not needed there, but, wondering what could be the reason?
For `make` in C++, please comment `// #define USE_Rcpp` in `utils.h` file.

**Comment by hroest** [comment]
I dont know, can you provde the command that you are using to build it in R ?

H

**Comment by shubham1637** [comment]
I mostly use Ctrl + Shift + B to build the package. I think under the hood, it is executing the following commands:
```
R CMD check DIAlignR
R CMD build DIAlignR
R CMD INSTALL DIAlignR_1.0.0.tar.gz
R
library(DIAlignR)
```
https://support.rstudio.com/hc/en-us/articles/200486488-Developing-Packages-with-RStudio

Regarding `using namespace DIAlign` in `src/RcppExports.cpp`: Based on 
https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-package.pdf
 I think:
Step 1: The `LinkingTo` declaration in the package `DESCRIPTION` file allows the client package to retrieve the headers of the target package (here Rcpp)
Step 2: `Rcpp` uses a function `Rcpp.package.skeleton`
Step 3: `Rcpp.package.skeleton` then invokes `compileAttributes()` on the package, which generates the `RcppExports.cpp` file, thus, removing manually added namespace.
Step 4. `Rcpp.package.skeleton` also generates `RcppExports.R` file which has `.Call()` functions pointing to functions defined in `RcppExports.cpp` which points to functions we write.
Step 5. `Rcpp.package.skeleton` also creates a `NAMESPACE` file which has all functions written with `[[Rcpp::export]]`. I think it uses `RcppExports.R` file to create it which in this process also has `@export` added to defined functions.

I am not sure how it finds our declared namespace although it is removed from `RcppExports.cpp` , but so far it works.

**Comment by hroest** [comment]
Well it works so that is what counts I guess

**Pull request merged**
